;;; site-functions.el --- -*- lexical-binding: t; -*-
(defvar todo-irl "~/org/todo/todo-irl.org")
(defvar todo-work "~/org/todo/work.org")
(defvar todo-it "~/org/todo/todo-it.org")
(defvar todo-school "~/org/school/work.org")

(defun soup6020/todo-open ()
  "Open primary org todo files in a 2x2 grid."
  (interactive)
  (delete-other-windows)
  (let* ((tl (selected-window))
         (bl (split-window tl nil 'below))
         (windows (list tl (split-window tl nil 'right)
                        bl (split-window bl nil 'right))))
    (seq-mapn (lambda (win file)
                (set-window-buffer win (find-file-noselect file)))
              windows
              (list todo-irl todo-work todo-it todo-school))
    (balance-windows)
    (select-window tl)))

(defun soup6020/indent-buffer ()
  "Indent the entire buffer."
  (interactive)
  (indent-region (point-min) (point-max)))

(defvar soup6020/man-trees
  '(("openbsd" . "~/Documents/man/openbsd/usr/share/man")
    ("illumos" . "~/Documents/man/illumos/usr/src/man"))
  "Alist mapping a system name to a local tree of its manual pages.")

(defun soup6020/man-page-table (tree)
  "Return a hash table mapping page names to their sections under TREE."
  (let ((table (make-hash-table :test #'equal)))
    (dolist (dir (directory-files (expand-file-name tree) t "\\`man[0-9]"))
      (when (file-directory-p dir)
        (dolist (file (directory-files dir nil "\\.[0-9][a-z]*\\'"))
          (push (file-name-extension file)
                (gethash (file-name-sans-extension file) table)))))
    table))

;;; This following function depends on scripts generated by Nix, as well as the respective documents actually being available as defined above. Search ~/nix for man-illumos for more details.
(defun soup6020/man-foreign (system topic)
  "Display a manual page from a foreign system."
  (interactive
   (let* ((system (completing-read "System: " soup6020/man-trees nil t))
          (table (soup6020/man-page-table (cdr (assoc system soup6020/man-trees))))
          (completion-extra-properties
           (list :annotation-function
                 (lambda (cand)
                   (propertize
                    (concat "  " (mapconcat (lambda (s) (format "(%s)" s))
                                            (sort (gethash cand table) #'string<)
                                            " "))
                    'face 'completions-annotations)))))
     (list system (completing-read (format "%s page: " system) table nil t))))
  (let ((manual-program (concat "man-" system))
        (Man-switches ""))
    (man topic)))

(provide 'site-functions)
